module.exports = {
  caseType:'dispatcher_bed_allocation', initialState:'request_received',
  states:['request_received','sources_synchronized','compatibility_review','allocation_proposed','dispatcher_approved','transfer_active','cleaning_required','available','closed'],
  createRoles:['bed_coordinator','dispatcher'],
  evidenceKinds:['adt_event_digest','bed_state_snapshot','patient_constraint_digest','staffing_snapshot','evs_status','transport_status','forecast_manifest','override_record'],
  requiredSignals:['sourceTimestamp','evaluatedAt','staleAfterSeconds','bedStateVersion','constraintVersion','staffingCoverage','cleaningStatus','policyVersion'],
  assessmentRoles:['bed_coordinator','dispatcher','clinical_flow_nurse'],
  auditRoles:['bed_coordinator','dispatcher','clinical_flow_nurse'],
  connectorRoles:['bed_coordinator','dispatcher'],
  professionalBoundary:'Allocation remains advisory; stale or conflicting data fails closed and an authorized clinical or operations dispatcher approves action.',
  connectors:[
    {name:'adt_fhir',purpose:'patient movement and constraint digests'},
    {name:'bed_management',purpose:'versioned bed-state snapshots'},
    {name:'staffing',purpose:'coverage status'},
    {name:'evs',purpose:'cleaning status'},
    {name:'transport',purpose:'transfer readiness'},
    {name:'command_center',purpose:'dispatcher receipt and override records'},
  ],
  transitions:[
    {from:'request_received',action:'synchronize_sources',to:'sources_synchronized',roles:['bed_coordinator'],requiresEvidence:true},
    {from:'sources_synchronized',action:'review_compatibility',to:'compatibility_review',roles:['bed_coordinator','clinical_flow_nurse'],requiresEvidence:true},
    {from:'compatibility_review',action:'propose_allocation',to:'allocation_proposed',roles:['bed_coordinator'],requiresEvidence:true},
    {from:'allocation_proposed',action:'approve',to:'dispatcher_approved',roles:['dispatcher','clinical_flow_nurse'],requiresEvidence:true,dualControl:true},
    {from:'dispatcher_approved',action:'start_transfer',to:'transfer_active',roles:['dispatcher'],requiresEvidence:true},
    {from:'transfer_active',action:'request_cleaning',to:'cleaning_required',roles:['dispatcher','evs'],requiresEvidence:true},
    {from:'cleaning_required',action:'mark_available',to:'available',roles:['evs'],requiresEvidence:true,dualControl:true},
    {from:'available',action:'close',to:'closed',roles:['bed_coordinator'],requiresEvidence:true,dualControl:true},
  ],
  assess:x=>{const source=Date.parse(x.sourceTimestamp);const evaluated=Date.parse(x.evaluatedAt);const limit=Number(x.staleAfterSeconds);const invalid=!Number.isFinite(source)||!Number.isFinite(evaluated)||!Number.isFinite(limit)||limit<=0||evaluated<source;const stale=invalid||(evaluated-source)/1000>limit;return{disposition:stale||x.staffingCoverage!=='adequate'||x.cleaningStatus!=='complete'?'fail_safe_no_allocation':'dispatcher_compatibility_review_required',allocation:null,stale,versions:{bed:x.bedStateVersion,constraints:x.constraintVersion}};},
};
